version: '3.8'

services:
  app:
    container_name: sentry
    build: .
    command: npm run start:dev
    ports:
      - '5000:5000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
